server:
  port: 18181
  servlet:
    session:
      cookie:
        name: KSESSION

security:
    oauth2:
      client:
        client-id: mobileapp
        client-secret: passcode123
        user-authorization-uri: http://localhost:9192/oauth/authorize
        access-token-uri: http://localhost:9192/oauth/token
      resource:
        token-info-uri: http://localhost:9192/oauth/check_token
